name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t pulsar1812/docker-react-test -f Dockerfile.dev .
      - run: docker run -e CI=true pulsar1812/docker-react-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: Docker React Test
          environment_name: DockerReactTest-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-1-851520880946
          region: ap-southeast-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
